<a href="https://colab.research.google.com/github/immaximo/Hybrid-ML-LLM-Tutoring-Model-for-Cloud-Certification-Preparation-/blob/main/Hybrid_en_GNNKT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.cuda.is_available()

False

In [ ]:
import torch
!pip install torch torchvision

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.25.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install torch_geometric

Requirement already satisfied: torch_geometric in /usr/local/lib/python3.12/dist-packages (2.7.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.13.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch_geometric) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2026.2.25)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch_geometric) (4.15.0)

In [ ]:
import pandas as pd
import numpy as np
import torch

from torch_geometric.data import Data

# Load datasets here
interactions = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/synchronized_interaction_logs.csv")
questions = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/CDL_150_Questions_With_ID.xlsx")
googlequestions = pd.read_json("/content/drive/MyDrive/Colab Notebooks/google_cloud_quiz_eval.json")
studentquiz = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/student_quiz_dataset.csv")

# For matching data
questions = questions.rename(columns={'Question_ID': 'question_id'})
questions['skill_id'] = questions['Module']
interactions = interactions.rename(columns={'student_id': 'user_id'})
studentquiz = studentquiz.rename(columns={'student_id': 'user_id'})


interactions = interactions.merge(studentquiz[['user_id', 'question_id', 'status']],
                                  on=['user_id', 'question_id'],
                                  how='left')


interactions['correct'] = interactions['status'].map({'correct': 1, 'incorrect': 0}).fillna(0).astype(int)

# Drop the original status column as it's no longer needed
interactions = interactions.drop(columns=['status'], errors='ignore')

# Merge interaction and skills
data = interactions.merge(questions, on="question_id", how="inner")
data = data.sort_values(by=["user_id", "timestamp"])

# IDs
user2idx = {u: i for i, u in enumerate(data["user_id"].unique())}
q2idx = {q: i for i, q in enumerate(data["question_id"].unique())}
s2idx = {s: i for i, s in enumerate(data["skill_id"].unique())}

data["user_id"] = data["user_id"].map(user2idx)
data["question_id"] = data["question_id"].map(q2idx)
data["skill_id"] = data["skill_id"].map(s2idx)

num_users = len(user2idx)
num_skills = len(s2idx)

# Student Sequences
student_sequences = []
grouped = data.groupby("user_id")

for user, group in grouped:
    student_sequences.append({
        "student_id": user,
        "q_seq": torch.tensor(group["question_id"].values, dtype=torch.long),
        "s_seq": torch.tensor(group["skill_id"].values, dtype=torch.long),
        "r_seq": torch.tensor(group["correct"].values, dtype=torch.float)
    })

# Skill graph
adj_matrix = np.zeros((num_skills, num_skills))
for seq in student_sequences:
    skills = seq["s_seq"].numpy()
    for i in range(len(skills)-1):
        s1, s2 = skills[i], skills[i+1]
        adj_matrix[s1, s2] += 1
        adj_matrix[s2, s1] += 1

edges = np.array(np.nonzero(adj_matrix))
edge_index = torch.tensor(edges, dtype=torch.long)
edge_weight = torch.tensor(adj_matrix[edges[0], edges[1]], dtype=torch.float)

x = torch.eye(num_skills, dtype=torch.float)

# Create PyG data object
data_gnn = Data(x=x, edge_index=edge_index, edge_attr=edge_weight)
data_gnn.student_sequences = student_sequences

# Save
torch.save(data_gnn, "kt_all_models_prepost.pt")
print("Preprocessing complete. Dataset ready for all models (AKT, DKT, SAKT, GRKT/GNN).")

Preprocessing complete. Dataset ready for all models (AKT, DKT, SAKT, GRKT/GNN).

<h1>GNN MODEL</H1>

In [ ]:
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class GNNKTModel(nn.Module):
    def __init__(self, num_skills, hidden_dim, output_dim, n_layers=1):
        super(GNNKTModel, self).__init__()
        self.num_skills = num_skills
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim
        self.n_layers = n_layers

        # GNN for skill embedding (using GCNConv)
        # Input to GCN is a one-hot encoding of skills
        self.conv1 = GCNConv(num_skills, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim) # Additional layer

        # GRU for sequential modeling of student interactions
        # Input to GRU will be concatenation of question embedding (skill embedding) and correctness
        # So, input_size for GRU will be hidden_dim (for skill embedding) + 1 (for correctness)
        self.gru = nn.GRU(input_size=hidden_dim + 1, hidden_size=hidden_dim, num_layers=n_layers, batch_first=True)

        # Output layer to predict correctness
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, s_seq, r_seq, edge_index, edge_attr, x_skills):
        # 1. Generate skill embeddings using GNN
        # x_skills are the one-hot encoded skill features (num_skills x num_skills identity matrix)
        skill_embeddings = F.relu(self.conv1(x_skills, edge_index, edge_attr))
        skill_embeddings = F.relu(self.conv2(skill_embeddings, edge_index, edge_attr))

        # 2. Prepare input for GRU
        # For each interaction in the sequence, get its corresponding skill embedding
        # s_seq contains skill indices
        current_skill_embeddings = skill_embeddings[s_seq] # Shape: (batch_size, seq_len, hidden_dim)

        # Concatenate skill embeddings with past response (r_seq)
        # r_seq needs to be unsqueezed to match dimensions
        gru_input = torch.cat((current_skill_embeddings, r_seq.unsqueeze(-1)), dim=-1) # Shape: (batch_size, seq_len, hidden_dim + 1)

        # 3. Process sequence with GRU
        gru_output, _ = self.gru(gru_input)

        # 4. Predict correctness for the next interaction
        # We are predicting the correctness of the *next* interaction, so shift the target
        # The GRU output at step t predicts the outcome at step t+1
        # For training, we usually predict all steps and compare with shifted ground truth.
        predictions = self.fc(gru_output) # Shape: (batch_size, seq_len, output_dim)

        return predictions.squeeze(-1) # Squeeze output_dim if it's 1

print("GNNKTModel architecture defined.")

GNNKTModel architecture defined.

<H1>TRAINING AND ACCURACY EVALUATION

In [ ]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.48)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [ ]:
!pip install pytorch_optimizer

Requirement already satisfied: pytorch_optimizer in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.12/dist-packages (from pytorch_optimizer) (2.0.2)
Requirement already satisfied: torch>=1.10 in /usr/local/lib/python3.12/dist-packages (from pytorch_optimizer) (2.10.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.10->pytorch_optimizer) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10->pytorch_optimizer) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.10->pytorch_optimizer) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10->pytorch_optimizer) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10->pytorch_optimizer) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10->pytorch_optimizer) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10->pytorch_optimizer) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.10->pytorch_optimizer) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.10->pytorch_optimizer) (3.0.3)

In [ ]:
import optuna
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, mean_squared_error
from pytorch_optimizer import SAM

def objective(trial):
    # Hyperparameters
    hidden_dim = trial.suggest_categorical('hidden_dim', [32, 64, 128])
    learning_rate = trial.suggest_float('learning_rate', 1e-5, 1e-2, log=True)
    n_layers = trial.suggest_int('n_layers', 1, 3)
    rho = trial.suggest_float('rho', 0.01, 0.2, log=True)
    n_epochs = 5

    output_dim = 1

    model = GNNKTModel(num_skills, hidden_dim, output_dim, n_layers)

    base_optimizer = optim.Adam
    optimizer = SAM(model.parameters(), base_optimizer, lr=learning_rate, rho=rho)
    criterion = nn.BCEWithLogitsLoss()

    train_sequences, test_sequences = train_test_split(data_gnn.student_sequences, test_size=0.2, random_state=42)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model.to(device)
    edge_index = data_gnn.edge_index.to(device)
    edges_attr = data_gnn.edge_attr.to(device)
    x_skills = data_gnn.x.to(device)

    print(f"\n--- Starting Trial {trial.number} ---")
    print(f"Params: hidden_dim={hidden_dim}, lr={learning_rate:.6f}, n_layers={n_layers}, rho={rho:.4f}")

    # SAM
    for epoch in range(n_epochs):
        model.train()
        total_loss = 0
        for student_data in train_sequences:
            q_seq = student_data['q_seq'].to(device)
            s_seq = student_data['s_seq'].to(device)
            r_seq = student_data['r_seq'].to(device)

            if len(s_seq) > 1:
                predictions = model(s_seq[:-1].unsqueeze(0), r_seq[:-1].unsqueeze(0), edge_index, edges_attr, x_skills)
                target = r_seq[1:].unsqueeze(0)
                loss = criterion(predictions, target)
                loss.backward()
                optimizer.first_step(zero_grad=True)

                predictions_second = model(s_seq[:-1].unsqueeze(0), r_seq[:-1].unsqueeze(0), edge_index, edges_attr, x_skills)
                loss_second = criterion(predictions_second, target)
                loss_second.backward()
                optimizer.second_step(zero_grad=True)

                total_loss += loss.item()
        print(f"Epoch {epoch+1}/{n_epochs}, Loss: {total_loss/len(train_sequences):.4f}")

    # Evaluation
    print(f"Evaluating Trial {trial.number} on test set...")
    model.eval()
    all_predictions = []
    all_targets = []

    with torch.no_grad():
        for student_data in test_sequences:
            q_seq = student_data['q_seq'].to(device)
            s_seq = student_data['s_seq'].to(device)
            r_seq = student_data['r_seq'].to(device)

            if len(s_seq) > 1:
                predictions = model(s_seq[:-1].unsqueeze(0), r_seq[:-1].unsqueeze(0), edge_index, edges_attr, x_skills)
                target = r_seq[1:].unsqueeze(0)

                probabilities = torch.sigmoid(predictions)

                all_predictions.extend(probabilities.cpu().numpy().flatten().tolist())
                all_targets.extend(target.cpu().numpy().flatten().tolist())

    # Calculate AUC and RMSE
    if len(all_targets) > 0:
        auc = roc_auc_score(all_targets, all_predictions)
        rmse = torch.sqrt(torch.tensor(mean_squared_error(all_targets, all_predictions), dtype=torch.float32)).item()
        print(f"=> Trial {trial.number} finished. AUC: {auc:.4f}, RMSE: {rmse:.4f}")
        return auc
    else:
        print(f"=> Trial {trial.number} finished. No sufficient data for evaluation.")
        return 0.0

In [ ]:
import optuna

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=5)

print("Number of finished trials: ", len(study.trials))
print("Best trial:")

trial = study.best_trial

print("  Value: ", trial.value)
print("  Params: ")
for key, value in trial.params.items():
    print("    {}: {}".format(key, value))

[I 2026-03-30 11:36:14,360] A new study created in memory with name: no-name-36c72ae5-7bae-4b20-87d6-48b69dcf42fa

--- Starting Trial 0 ---
Params: hidden_dim=128, lr=0.000665, n_layers=2, rho=0.1964
Epoch 1/5, Loss: 0.5750
Epoch 2/5, Loss: 0.5601
Epoch 3/5, Loss: 0.5572
Epoch 4/5, Loss: 0.5469
Epoch 5/5, Loss: 0.5343
Evaluating Trial 0 on test set...

[I 2026-03-30 12:02:50,401] Trial 0 finished with value: 0.7613737622202716 and parameters: {'hidden_dim': 128, 'learning_rate': 0.0006652900818768577, 'n_layers': 2, 'rho': 0.19642978039866743}. Best is trial 0 with value: 0.7613737622202716.

=> Trial 0 finished. AUC: 0.7614, RMSE: 0.4102

--- Starting Trial 1 ---
Params: hidden_dim=128, lr=0.008227, n_layers=2, rho=0.0533
Epoch 1/5, Loss: 0.5670
Epoch 2/5, Loss: 0.5593
Epoch 3/5, Loss: 0.5507
Epoch 4/5, Loss: 0.5383
Epoch 5/5, Loss: 0.5277
Evaluating Trial 1 on test set...

[I 2026-03-30 12:29:12,825] Trial 1 finished with value: 0.770786331373707 and parameters: {'hidden_dim': 128, 'learning_rate': 0.008226738889727426, 'n_layers': 2, 'rho': 0.05334076293097795}. Best is trial 1 with value: 0.770786331373707.

=> Trial 1 finished. AUC: 0.7708, RMSE: 0.4080

--- Starting Trial 2 ---
Params: hidden_dim=32, lr=0.008648, n_layers=2, rho=0.0152
Epoch 1/5, Loss: 0.5658
Epoch 2/5, Loss: 0.5618
Epoch 3/5, Loss: 0.5618
Epoch 4/5, Loss: 0.5597
Epoch 5/5, Loss: 0.5626
Evaluating Trial 2 on test set...

[I 2026-03-30 12:50:38,008] Trial 2 finished with value: 0.6609311799616508 and parameters: {'hidden_dim': 32, 'learning_rate': 0.008648486477647504, 'n_layers': 2, 'rho': 0.01516791562699527}. Best is trial 1 with value: 0.770786331373707.

=> Trial 2 finished. AUC: 0.6609, RMSE: 0.4385

--- Starting Trial 3 ---
Params: hidden_dim=128, lr=0.000017, n_layers=1, rho=0.0692
Epoch 1/5, Loss: 0.5975
Epoch 2/5, Loss: 0.5839
Epoch 3/5, Loss: 0.5814
Epoch 4/5, Loss: 0.5797
Epoch 5/5, Loss: 0.5784
Evaluating Trial 3 on test set...

[I 2026-03-30 13:04:38,025] Trial 3 finished with value: 0.6057068200892739 and parameters: {'hidden_dim': 128, 'learning_rate': 1.683753813000264e-05, 'n_layers': 1, 'rho': 0.06920198326500689}. Best is trial 1 with value: 0.770786331373707.

=> Trial 3 finished. AUC: 0.6057, RMSE: 0.4484

--- Starting Trial 4 ---
Params: hidden_dim=64, lr=0.000030, n_layers=3, rho=0.0718
Epoch 1/5, Loss: 0.5961
Epoch 2/5, Loss: 0.5854
Epoch 3/5, Loss: 0.5822
Epoch 4/5, Loss: 0.5798
Epoch 5/5, Loss: 0.5776
Evaluating Trial 4 on test set...

[I 2026-03-30 13:36:55,711] Trial 4 finished with value: 0.6119133286413451 and parameters: {'hidden_dim': 64, 'learning_rate': 3.0232556117612367e-05, 'n_layers': 3, 'rho': 0.07176228634130083}. Best is trial 1 with value: 0.770786331373707.

=> Trial 4 finished. AUC: 0.6119, RMSE: 0.4478
Number of finished trials:  5
Best trial:
  Value:  0.770786331373707
  Params:
    hidden_dim: 128
    learning_rate: 0.008226738889727426
    n_layers: 2
    rho: 0.05334076293097795

<h1>LATENCY

In [ ]:
import time
import torch
import pandas as pd # Ensure pandas is imported

print("Starting interactive latency test (3 runs)...\n")

for run in range(3):
    try:
        user_input = input(f"Run {run + 1}/3 - Please enter a Question ID: ")
        q_id_orig = int(user_input)
    except ValueError:
        print("Invalid input. Please enter a valid numerical Question ID.\n")
        continue

    # Record start time just before fetching the question
    start_time = time.perf_counter()

    # Fetch question details
    q_row = questions[questions['question_id'] == q_id_orig]
    if q_row.empty:
        print(f"Question ID {q_id_orig} not found in the dataset.\n")
        continue

    question_text = q_row['Question'].iloc[0]

    # Record end time immediately after fetching the question
    end_time = time.perf_counter()

    latency_ms = (end_time - start_time) * 1000

    # Print Results
    print(f"\n--- Results ---")
    print(f"Question ID: {q_id_orig}")
    print(f"Question: {question_text}")
    print(f"Latency for question lookup: {latency_ms:.4f} ms\n")

Starting interactive latency test (3 runs)...

Run 1/3 - Please enter a Question ID: 40

--- Results ---
Question ID: 40
Question: What is object storage?
Latency for question lookup: 1.3085 ms

Run 2/3 - Please enter a Question ID: 50

--- Results ---
Question ID: 50
Question: What is AI?
Latency for question lookup: 1.7699 ms

Run 3/3 - Please enter a Question ID: 85

--- Results ---
Question ID: 85
Question: What is an API?
Latency for question lookup: 1.3303 ms

<h1>HYBRIDIZATION

<H2>API

In [ ]:
!pip install openai

import openai
from google.colab import userdata

OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')

client = openai.OpenAI(api_key=OPENAI_API_KEY)

print("OpenAI client initialized.")

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.30.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
OpenAI client initialized.

<h1>RAG

In [ ]:
!pip install sentence-transformers faiss-cpu rank_bm25

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.13.2)
Requirement already satisfied: rank_bm25 in /usr/local/lib/python3.12/dist-packages (0.2.2)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

In [ ]:
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
from rank_bm25 import BM25Okapi
import torch
import pandas as pd

questions = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/CDL_150_Questions_With_ID.xlsx")
questions = questions.rename(columns={'Question_ID': 'question_id'})

questions['skill_id'] = questions['Module']

# Dense Retrieval Setup
print("\n--- Setting up Dense Retrieval ---")

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

question_texts = questions['Question'].tolist()
question_embeddings = embedding_model.encode(question_texts, convert_to_tensor=False)

print(f"Generated {len(question_embeddings)} embeddings of dimension {question_embeddings.shape[1]}.")
print(f"First embedding snippet: {question_embeddings[0][:5]}...")

dimension = question_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension) # Using L2 distance for similarity
index.add(question_embeddings.astype('float32')) # FAISS requires float32

print(f"FAISS index created with {index.ntotal} vectors.")

# Sparse Retrieval Setup
print("\n--- Setting up Sparse Retrieval ---")

tokenized_corpus = [doc.lower().split(" ") for doc in question_texts]
bm25 = BM25Okapi(tokenized_corpus)

print("BM25 index created.")

--- Setting up Dense Retrieval ---

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Generated 150 embeddings of dimension 384.
First embedding snippet: [-0.0426912   0.03437556 -0.10072621 -0.09831116 -0.05000662]...
FAISS index created with 150 vectors.

--- Setting up Sparse Retrieval ---
BM25 index created.

In [ ]:
import pandas as pd
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
from rank_bm25 import BM25Okapi

# 1. Load the Curriculum Dataset
curriculum_path = "/content/drive/MyDrive/Colab Notebooks/cdl-TOPIC_DATASET.xlsx"
df_curriculum = pd.read_excel(curriculum_path)

# 2. Prepare text for embedding (combining Topic and Definition)
df_curriculum['rag_text'] = "Topic: " + df_curriculum['Topic'].astype(str) + " | Definition: " + df_curriculum['Definition'].astype(str)
curriculum_texts = df_curriculum['rag_text'].tolist()

# 3. Build Dense Index
print("Building Dense Index for Curriculum...")
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
curriculum_embeddings = embedding_model.encode(curriculum_texts, convert_to_tensor=False)
dimension = curriculum_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(curriculum_embeddings.astype('float32'))

# 4. Build Sparse Index
print("Building Sparse Index for Curriculum...")
tokenized_corpus = [doc.lower().split(" ") for doc in curriculum_texts]
bm25 = BM25Okapi(tokenized_corpus)

print("Indexes built successfully!\n")

def hybrid_search(query, top_k=5):
    # 1. Dense Retrieval
    query_embedding = embedding_model.encode([query]).astype('float32')
    distances, dense_indices = index.search(query_embedding, top_k)
    dense_results = dense_indices[0].tolist()

    # 2. Sparse Retrieval
    tokenized_query = query.lower().split(" ")
    bm25_scores = bm25.get_scores(tokenized_query)
    sparse_results = np.argsort(bm25_scores)[::-1][:top_k].tolist()

    # 3. RRF Combination
    rrf_scores = {}
    for rank, idx in enumerate(dense_results):
        rrf_scores[idx] = rrf_scores.get(idx, 0.0) + 1.0 / (60 + rank + 1)
    for rank, idx in enumerate(sparse_results):
        rrf_scores[idx] = rrf_scores.get(idx, 0.0) + 1.0 / (60 + rank + 1)

    combined_results = sorted(rrf_scores.items(), key=lambda x: x[1], reverse=True)[:top_k]
    final_indices = [idx for idx, score in combined_results]

    # 4. Fetch the actual curriculum context
    retrieved_context = df_curriculum.iloc[final_indices].copy()

    # Map columns so the downstream LLM pipeline can read them properly!
    retrieved_context['skill_id'] = retrieved_context['Topic']
    retrieved_context['Question'] = retrieved_context['Topic']
    retrieved_context['Explanation'] = retrieved_context['Definition']

    return retrieved_context

# Let's test the hybrid search with a sample query
test_query = "What is machine learning?"
print(f"Query: {test_query}\n")
results = hybrid_search(test_query, top_k=3)
display(results[['Topic', 'Definition']])

Building Dense Index for Curriculum...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Building Sparse Index for Curriculum...
Indexes built successfully!

Query: What is machine learning?

                     Topic                                         Definition
155        Executing ML ML    The process of running machine learning models.
46   Machine learning (ML)  Branch of AI where computers learn from data a...
86           Authorization          Determining what a user is allowed to do.

Check for column names

In [ ]:
import pandas as pd

curriculum_path = "/content/drive/MyDrive/Colab Notebooks/cdl-TOPIC_DATASET.xlsx"

try:
    df_curriculum = pd.read_excel(curriculum_path)
    print("--- Curriculum Dataset Columns ---")
    print(df_curriculum.columns.tolist())
    print("\n--- First 2 rows ---")
    display(df_curriculum.head(2))
except Exception as e:
    print(f"Error loading curriculum: {e}")

--- Curriculum Dataset Columns ---
['ID', 'Course #', 'Module #', 'Topic', 'Definition', 'Examples', 'Related Topics']

--- First 2 rows ---

,ID,Course #,Module #,Topic,Definition,Examples,Related Topics
0,1,Course 1,Module 1,Digital Transformation,When an organization uses new technologies to ...,Modifying business processes; culture; and cus...,Innovation; Cloud Technology
1,2,Course 1,Module 1,Cloud technology,The technology and processes needed to store; ...,Data accessed via internet vs. local hard drive.,Compute power; Computing

High-Scores

In [ ]:
import pandas as pd

# File paths
STUDENT_ANSWERS_CSV_PATH = "/content/drive/MyDrive/Colab Notebooks/high_score_test.csv"
CDL_TOPIC_DATASET_PATH = "/content/drive/MyDrive/Colab Notebooks/cdl-TOPIC_DATASET.xlsx"
QUIZ_ANSWER_KEY_PATH = "/content/drive/MyDrive/Colab Notebooks/quiz_answer_key.csv"

# Column name config
COL_QUESTION_ID = 'question_id'
COL_STUDENT_ANSWER = 'answer'
COL_CORRECT_ANSWER = 'correct_answer_label'

def generate_personalized_study_guide(csv_path, curriculum_path, answer_key_path):
    print(f"Loading student answers from: {csv_path}")
    print(f"Loading answer key from: {answer_key_path}")
    print(f"Loading curriculum dataset from: {curriculum_path}")

    # Load datasets
    try:
        student_answers = pd.read_csv(csv_path)
        answer_key = pd.read_csv(answer_key_path)
        cdl_curriculum = pd.read_excel(curriculum_path)
    except FileNotFoundError as e:
        return f"File not found error: {e}\nPlease check the paths and try again."

    # Check student answers against the answer key
    if COL_QUESTION_ID not in student_answers.columns or COL_QUESTION_ID not in answer_key.columns:
        return f"Error: Both CSVs must contain a '{COL_QUESTION_ID}' column to match them up."

    merged = pd.merge(student_answers, answer_key, on=COL_QUESTION_ID, how='left')

    if COL_STUDENT_ANSWER not in merged.columns or COL_CORRECT_ANSWER not in merged.columns:
        return f"Error: Check column names. Could not find '{COL_STUDENT_ANSWER}' or '{COL_CORRECT_ANSWER}' after merging."

    # Create a boolean correctness column by comparing strings (ignoring case and whitespace)
    merged['is_correct'] = (
        merged[COL_STUDENT_ANSWER].astype(str).str.strip().str.lower() ==
        merged[COL_CORRECT_ANSWER].astype(str).str.strip().str.lower()
    ).astype(int)

    # Filter questions for the study guide
    incorrect_answers = merged[merged['is_correct'] == 0]
    perfect_score = False

    if incorrect_answers.empty:
        print("Perfect score detected! Generating a comprehensive review guide based on all answered questions...")
        target_questions = merged
        perfect_score = True
    else:
        print(f"Found {len(incorrect_answers)} incorrect answers. Gathering context from Hybrid RAG...")
        target_questions = incorrect_answers

    # Gather context using our Hybrid RAG for the targeted topics/questions
    rag_context = ""
    for index, row in target_questions.iterrows():
        # Use the question ID or topic to search our RAG
        search_query = str(row.get('topic', f"Question ID {row.get(COL_QUESTION_ID)} concept"))

        # Fetch top 3 most relevant context blocks to expand the scope
        rag_results = hybrid_search(search_query, top_k=3)

        # Append the retrieved content (including Related Topics) to our context
        for _, q_row in rag_results.iterrows():
            rag_context += f"Topic: {q_row.get('Topic', 'Unknown')}\n"
            rag_context += f"Definition: {q_row.get('Definition', '')}\n"
            # Include related topics from the dataset so the LLM can expand the study guide
            rag_context += f"Related Topics to Mention: {q_row.get('Related Topics', 'None')}\n\n"

    # Inject context into LLM (OpenAI GPT API)
    print("Generating study guide via OpenAI API...")

    if perfect_score:
        prompt_intro = "A student has just taken a practice exam and got a perfect score! Provide an extremely comprehensive, advanced reviewer to reinforce and deepen their knowledge on these topics."
    else:
        prompt_intro = "A student has just taken a practice exam and got several topics wrong. Provide a personalized, extensively detailed reviewer to help them deeply understand their mistakes and master the material."

    prompt = f"""
    You are an expert Google Cloud Digital Leader tutor.
    {prompt_intro}

    CRITICAL INSTRUCTIONS:
    1. CLEAN PLAIN TEXT ONLY: DO NOT use any Markdown formatting. NO asterisks (*), NO hashtags (#), NO underscores (_), and NO bold/italic formatting. Use ALL CAPS for headers, simple numbers (1., 2.), and clean line breaks to structure your output.
    2. BE HIGHLY DESCRIPTIVE & CONTEXTUAL: Provide a massive, extensive, and comprehensive reviewer. Do not give brief summaries. Tie everything back to Google Cloud principles, business values, and real-world environments.
    3. MENTION RELATED TOPICS: In the context below, there are "Related Topics" listed for the main concepts. You MUST weave these related topics into your explanations to expand the length and depth of the study guide. Show how they connect!
    4. NO CRITIQUE: DO NOT critique the quiz itself or mention test format. Focus purely on teaching.

    For every topic the student needs to review, you MUST format the output strictly as follows:

    TOPIC: [TOPIC NAME IN ALL CAPS]

    DESCRIPTION AND IN-DEPTH EXPLANATION:
    (A comprehensive and highly detailed explanation of the concept and its contextual importance in Google Cloud.)

    RELATED CONCEPTS TO KNOW:
    (Explain the related topics provided in the context. Show how they interconnect with the main topic to build a broader understanding.)

    REAL-WORLD EXAMPLES:
    (Detailed, practical examples illustrating exactly how this concept is applied in a business or cloud environment.)

    GUIDE QUESTIONS:
    (3 to 5 thought-provoking questions to thoroughly test their understanding.)

    Context from Curriculum (Including Related Topics):
    {rag_context}

    Please provide the structured, extensive, plain-text reviewer now.
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are a highly professional, exhaustive, and helpful cloud tutor."},
                {"role": "user", "content": prompt}
            ],
            max_completion_tokens=4000
        )
        llm_response_content = response.choices[0].message.content
        print(f"LLM Response Content Length: {len(llm_response_content)}")
        print(f"LLM Response Content (first 500 chars):\n{llm_response_content[:500]}")
        return llm_response_content
    except Exception as e:
        return f"Error calling OpenAI API: {e}"

# EXECUTE THE PIPELINE

final_study_guide = generate_personalized_study_guide(STUDENT_ANSWERS_CSV_PATH, CDL_TOPIC_DATASET_PATH, QUIZ_ANSWER_KEY_PATH)
print("\n================ GENERATED STUDY GUIDE ================\n")
print(final_study_guide)
print("\n=======================================================\n")

Loading student answers from: /content/drive/MyDrive/Colab Notebooks/high_score_test.csv
Loading answer key from: /content/drive/MyDrive/Colab Notebooks/quiz_answer_key.csv
Loading curriculum dataset from: /content/drive/MyDrive/Colab Notebooks/cdl-TOPIC_DATASET.xlsx
Found 10 incorrect answers. Gathering context from Hybrid RAG...
Generating study guide via OpenAI API...
LLM Response Content Length: 7588
LLM Response Content (first 500 chars):
TOPIC: NEW VALUE VALUE

DESCRIPTION AND IN-DEPTH EXPLANATION:
In the modern digital world, the explosion of data has led businesses to seek ways to extract meaningful insights to gain a competitive edge. By discovering previously hidden benefits in their data, organizations can unlock new value. This involves a process of transforming raw data into actionable insights that can impact decision-making, customer engagement, and strategy formulation. The goal is to use analytics and data to discov

================ GENERATED STUDY GUIDE ================

TOPIC: NEW VALUE VALUE

DESCRIPTION AND IN-DEPTH EXPLANATION:
In the modern digital world, the explosion of data has led businesses to seek ways to extract meaningful insights to gain a competitive edge. By discovering previously hidden benefits in their data, organizations can unlock new value. This involves a process of transforming raw data into actionable insights that can impact decision-making, customer engagement, and strategy formulation. The goal is to use analytics and data to discover trends, predict behaviors, and identify opportunities that would otherwise remain unnoticed. Google Cloud provides a rich suite of tools and services such as BigQuery, Dataflow, and Looker to assist organizations in deriving new value from their data. These tools enable efficient data processing, advanced querying, and intuitive visualization, simplifying the process of turning data into insights.

RELATED CONCEPTS TO KNOW:
Insights: Insights refer to the deep understanding or knowledge gained from the data analytics process. They transform data from simply being numbers and figures into meaningful patterns that can inform strategic decisions. In Google Cloud, insights are often gathered using machine learning and data analytics tools that can handle both structured and unstructured data, supporting both real-time and batch processing. This enables businesses to quickly adjust to market trends and optimize operations based on newfound knowledge.

REAL-WORLD EXAMPLES:
Retail companies, for instance, analyze customer purchasing data to identify shopping patterns and preferences. By understanding these patterns, they can optimize their stock, personalize marketing efforts, and improve customer satisfaction, thus generating additional value. In another example, a healthcare organization may use data insights to track patient outcomes, optimize treatment protocols, and anticipate healthcare needs before critical issues arise.

GUIDE QUESTIONS:
1. How can organizations identify and prioritize which data sources will most likely produce new insights of value?
2. What roles do data analytics platforms like BigQuery and Looker play in deriving new value from data?
3. In what ways can insights obtained from data analytics influence business strategy and operations?
4. Describe how machine learning can enhance the process of extracting insights from datasets.
5. What are potential risks or challenges businesses may face when trying to extract new value from their data?

TOPIC: RELIABILITY AT SCALE SCALE

DESCRIPTION AND IN-DEPTH EXPLANATION:
Reliability at scale refers to the ability of large systems to maintain consistent performance and availability, even as the scale of operations grows. Google Cloud’s infrastructure is designed to deliver high reliability through features like auto-scaling, load balancing, and comprehensive monitoring tools. It ensures that applications remain robust and responsive, regardless of increased demand or traffic surges. This is critical for businesses, as downtime can lead to not only revenue loss but also a negative impact on customer trust and brand reputation. Key components that support reliability in Google Cloud include multi-cloud and hybrid cloud strategies, which offer resilience through diversity in cloud architecture and failover capabilities.

RELATED CONCEPTS TO KNOW:
SRE (Site Reliability Engineering): SRE is a discipline that incorporates aspects of software engineering and applies them to infrastructure and operations problems to create scalable and highly reliable systems. It emphasizes automation, continuous integration, and continuous delivery practices to maintain service uptime and reliability. SRE teams often work in tandem with development teams to build highly available systems that can handle a massive number of requests efficiently. Google’s SRE principles are integrated into the design and management of cloud services to ensure high availability and rapid recovery from failures.

REAL-WORLD EXAMPLES:
Consider a global e-commerce platform that uses Google Cloud services for its operations. By leveraging Google Cloud’s auto-scaling and global load balancers, it can maintain seamless user experience despite fluctuating traffic levels during shopping seasons. Similarly, a financial institution running transactional applications in the cloud can use monitoring and alerting systems to ensure operational integrity, quickly responding to any reliability issues.

GUIDE QUESTIONS:
1. What are the critical features of Google Cloud that contribute to maintaining reliability at scale?
2. How does Site Reliability Engineering (SRE) enhance an organization’s capability to maintain high reliability in its cloud operations?
3. Describe the role of automation in ensuring system reliability and how it is applied within Google Cloud.
4. How can businesses mitigate the risks associated with system failures and ensure data recovery in cloud environments?
5. What are the implications of not establishing a reliable cloud infrastructure for large businesses?

TOPIC: ML PROBLEM TYPES

DESCRIPTION AND IN-DEPTH EXPLANATION:
Machine Learning (ML) problem types are the different categories of problems that artificial intelligence (AI) systems are designed to solve. Understanding these types is crucial in structuring AI projects and deploying ML models effectively. Common ML problem types include classification, regression, clustering, and recommendation. Each type addresses specific business needs such as predicting future trends, categorizing data, identifying patterns, and personalizing content. Google Cloud’s AI and ML offerings, such as Vertex AI, provide tools for building, deploying, and managing ML models across varied problem types. They facilitate the construction of scalable ML solutions with predefined algorithms and customizable options to fit specific organizational needs.

RELATED CONCEPTS TO KNOW:
AI Fundamentals: AI fundamentals encompass the basic principles and technologies underpinning artificial intelligence, including data mining, neural networks, and natural language processing. These principles support the development and improvement of AI systems, allowing them to learn from data, identify patterns, and make data-driven decisions. Mastery of AI fundamentals enables the effective deployment and operation of machine learning models across various Google Cloud applications.

REAL-WORLD EXAMPLES:
A financial institution may use classification algorithms to identify potentially fraudulent transactions based on spending patterns. Retailers could deploy recommendation systems to suggest products to customers, improving user experience and sales. Predictive models in healthcare can forecast patient admissions, aiding hospital resource allocation. By leveraging these AI models, businesses can derive actionable insights that directly contribute to operational efficiency and enhanced customer satisfaction.

GUIDE QUESTIONS:
1. What are the main differences between major ML problem types such as classification and regression?
2. How do AI fundamentals contribute to the successful deployment of machine learning models in solving business problems?
3. Describe how businesses can select the appropriate ML problem type for their specific data challenges.
4. What are some of the tools and resources provided by Google Cloud to facilitate ML model development for different problem types?
5. How do ethical considerations influence the design and deployment of machine learning models?

=======================================================

In [ ]:
# Save the deeply generated study guide to a Markdown/Text file in your Drive
output_file_path = "/content/drive/MyDrive/Colab Notebooks/CDL_Personalized_Reviewer.md"

try:
    with open(output_file_path, "w", encoding="utf-8") as f:
        f.write(final_study_guide)
    print(f"✅ Successfully saved the FULL reviewer to:\n{output_file_path}")
    print("You can now open this file in Google Drive to read the complete, untruncated study guide!")
except Exception as e:
    print(f"Error saving file: {e}")

✅ Successfully saved the FULL reviewer to:
/content/drive/MyDrive/Colab Notebooks/CDL_Personalized_Reviewer.md
You can now open this file in Google Drive to read the complete, untruncated study guide!

Checking column names

In [ ]:
import pandas as pd

student_csv = "/content/drive/MyDrive/Colab Notebooks/high_score_test.csv"
answer_key_csv = "/content/drive/MyDrive/Colab Notebooks/quiz_answer_key.csv"

print("--- Inspecting Student Answers CSV ---")
try:
    df_student = pd.read_csv(student_csv)
    print("Columns:", df_student.columns.tolist())
except Exception as e:
    print(f"Error reading student CSV: {e}")

print("\n--- Inspecting Answer Key CSV ---")
try:
    df_key = pd.read_csv(answer_key_csv)
    print("Columns:", df_key.columns.tolist())
except Exception as e:
    print(f"Error reading answer key CSV: {e}")

--- Inspecting Student Answers CSV ---
Columns: ['question_id', 'answer']

--- Inspecting Answer Key CSV ---
Columns: ['question_id', 'correct_answer_label', 'correct_answer_text']

Low-Scores

In [ ]:
import pandas as pd

# File paths
STUDENT_ANSWERS_CSV_PATH = "/content/drive/MyDrive/Colab Notebooks/low_score_test.csv"
CDL_TOPIC_DATASET_PATH = "/content/drive/MyDrive/Colab Notebooks/cdl-TOPIC_DATASET.xlsx"
QUIZ_ANSWER_KEY_PATH = "/content/drive/MyDrive/Colab Notebooks/quiz_answer_key.csv"

# Column name config
COL_QUESTION_ID = 'question_id'
COL_STUDENT_ANSWER = 'answer'
COL_CORRECT_ANSWER = 'correct_answer_label'

def generate_personalized_study_guide(csv_path, curriculum_path, answer_key_path):
    print(f"Loading student answers from: {csv_path}")
    print(f"Loading answer key from: {answer_key_path}")
    print(f"Loading curriculum dataset from: {curriculum_path}")

    # Load datasets
    try:
        student_answers = pd.read_csv(csv_path)
        answer_key = pd.read_csv(answer_key_path)
        cdl_curriculum = pd.read_excel(curriculum_path)
    except FileNotFoundError as e:
        return f"File not found error: {e}\nPlease check the paths and try again."

    # Check student answers against the answer key
    if COL_QUESTION_ID not in student_answers.columns or COL_QUESTION_ID not in answer_key.columns:
        return f"Error: Both CSVs must contain a '{COL_QUESTION_ID}' column to match them up."

    merged = pd.merge(student_answers, answer_key, on=COL_QUESTION_ID, how='left')

    if COL_STUDENT_ANSWER not in merged.columns or COL_CORRECT_ANSWER not in merged.columns:
        return f"Error: Check column names. Could not find '{COL_STUDENT_ANSWER}' or '{COL_CORRECT_ANSWER}' after merging."

    # Create a boolean correctness column by comparing strings (ignoring case and whitespace)
    merged['is_correct'] = (
        merged[COL_STUDENT_ANSWER].astype(str).str.strip().str.lower() ==
        merged[COL_CORRECT_ANSWER].astype(str).str.strip().str.lower()
    ).astype(int)

    # Filter questions for the study guide
    incorrect_answers = merged[merged['is_correct'] == 0]
    perfect_score = False

    if incorrect_answers.empty:
        print("Perfect score detected! Generating a comprehensive review guide based on all answered questions...")
        target_questions = merged
        perfect_score = True
    else:
        print(f"Found {len(incorrect_answers)} incorrect answers. Gathering context from Hybrid RAG...")
        target_questions = incorrect_answers

    # Gather context using our Hybrid RAG for the targeted topics/questions
    rag_context = ""
    for index, row in target_questions.iterrows():
        # Use the question ID or topic to search our RAG
        search_query = str(row.get('topic', f"Question ID {row.get(COL_QUESTION_ID)} concept"))

        # Fetch top 3 most relevant context blocks to expand the scope
        rag_results = hybrid_search(search_query, top_k=3)

        # Append the retrieved content (including Related Topics) to our context
        for _, q_row in rag_results.iterrows():
            rag_context += f"Topic: {q_row.get('Topic', 'Unknown')}\n"
            rag_context += f"Definition: {q_row.get('Definition', '')}\n"
            # Include related topics from the dataset so the LLM can expand the study guide
            rag_context += f"Related Topics to Mention: {q_row.get('Related Topics', 'None')}\n\n"

    # Inject context into LLM (OpenAI GPT API)
    print("Generating study guide via OpenAI API...")

    if perfect_score:
        prompt_intro = "A student has just taken a practice exam and got a perfect score! Provide an extremely comprehensive, advanced reviewer to reinforce and deepen their knowledge on these topics."
    else:
        prompt_intro = "A student has just taken a practice exam and got several topics wrong. Provide a personalized, extensively detailed reviewer to help them deeply understand their mistakes and master the material."

    prompt = f"""
    You are an expert Google Cloud Digital Leader tutor.
    {prompt_intro}

    CRITICAL INSTRUCTIONS:
    1. CLEAN PLAIN TEXT ONLY: DO NOT use any Markdown formatting. NO asterisks (*), NO hashtags (#), NO underscores (_), and NO bold/italic formatting. Use ALL CAPS for headers, simple numbers (1., 2.), and clean line breaks to structure your output.
    2. BE HIGHLY DESCRIPTIVE & CONTEXTUAL: Provide a massive, extensive, and comprehensive reviewer. Do not give brief summaries. Tie everything back to Google Cloud principles, business values, and real-world environments.
    3. MENTION RELATED TOPICS: In the context below, there are "Related Topics" listed for the main concepts. You MUST weave these related topics into your explanations to expand the length and depth of the study guide. Show how they connect!
    4. NO CRITIQUE: DO NOT critique the quiz itself or mention test format. Focus purely on teaching.

    For every topic the student needs to review, you MUST format the output strictly as follows:

    TOPIC: [TOPIC NAME IN ALL CAPS]

    DESCRIPTION AND IN-DEPTH EXPLANATION:
    (A comprehensive and highly detailed explanation of the concept and its contextual importance in Google Cloud.)

    RELATED CONCEPTS TO KNOW:
    (Explain the related topics provided in the context. Show how they interconnect with the main topic to build a broader understanding.)

    REAL-WORLD EXAMPLES:
    (Detailed, practical examples illustrating exactly how this concept is applied in a business or cloud environment.)

    GUIDE QUESTIONS:
    (3 to 5 thought-provoking questions to thoroughly test their understanding.)

    Context from Curriculum (Including Related Topics):
    {rag_context}

    Please provide the structured, extensive, plain-text reviewer now.
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are a highly professional, exhaustive, and helpful cloud tutor."},
                {"role": "user", "content": prompt}
            ],
            max_completion_tokens=4000
        )
        llm_response_content = response.choices[0].message.content
        print(f"LLM Response Content Length: {len(llm_response_content)}")
        print(f"LLM Response Content (first 500 chars):\n{llm_response_content[:500]}")
        return llm_response_content
    except Exception as e:
        return f"Error calling OpenAI API: {e}"

# EXECUTE THE PIPELINE

final_study_guide = generate_personalized_study_guide(STUDENT_ANSWERS_CSV_PATH, CDL_TOPIC_DATASET_PATH, QUIZ_ANSWER_KEY_PATH)
print("\n================ GENERATED STUDY GUIDE ================\n")
print(final_study_guide)
print("\n=======================================================\n")

Loading student answers from: /content/drive/MyDrive/Colab Notebooks/low_score_test.csv
Loading answer key from: /content/drive/MyDrive/Colab Notebooks/quiz_answer_key.csv
Loading curriculum dataset from: /content/drive/MyDrive/Colab Notebooks/cdl-TOPIC_DATASET.xlsx
Found 30 incorrect answers. Gathering context from Hybrid RAG...
Generating study guide via OpenAI API...
LLM Response Content Length: 9936
LLM Response Content (first 500 chars):
TOPIC: NEW VALUE VALUE

DESCRIPTION AND IN-DEPTH EXPLANATION:
"New value value" in the context of Google Cloud refers to the discovery of previously hidden benefits or insights within data through advanced data analysis and processing techniques. In today's corporate landscape, data is a pivotal asset. However, simply collecting data is not enough. The ability to extract meaningful insights from this data can critically transform business operations and strategies. Google Cloud provides an array

================ GENERATED STUDY GUIDE ================

TOPIC: NEW VALUE VALUE

DESCRIPTION AND IN-DEPTH EXPLANATION:
"New value value" in the context of Google Cloud refers to the discovery of previously hidden benefits or insights within data through advanced data analysis and processing techniques. In today's corporate landscape, data is a pivotal asset. However, simply collecting data is not enough. The ability to extract meaningful insights from this data can critically transform business operations and strategies. Google Cloud provides an array of services, such as BigQuery for data warehousing and Google Data Studio for visualization, that empower businesses to perform in-depth analyses on massive datasets.

The discovery of new value in data involves identifying trends, patterns, and opportunities that were previously not visible. This process can be enriched by utilizing Google Cloud's machine learning capabilities, such as TensorFlow or AutoML, to predict future trends or customer behaviors. Leveraging the scale, speed, and innovation of Google Cloud, organizations can differentiate themselves in highly competitive markets.

RELATED CONCEPTS TO KNOW:
Insights are a critical component of realizing the new value from data. Insights are actionable and meaningful conclusions drawn from data analysis, which can drive strategic business decisions and innovations. Google Cloud empowers businesses to gain insights using tools like Cloud AI Platform and Looker. By integrating insights with machine learning models, businesses can transform raw data into comprehensive reports, enabling more informed decision-making.

REAL-WORLD EXAMPLES:
Consider a retail company looking to optimize its inventory management. By leveraging Google Cloud's data tools, the company can analyze historical sales data and predict future demand, uncovering new value by optimizing stock levels to reduce excess inventory and improve cash flow. Another example could be a healthcare institution using Google Cloud to identify patterns in patient data that indicate the early onset of diseases, thus improving patient outcomes by enabling proactive treatment strategies.

GUIDE QUESTIONS:
1. How can businesses leverage Google Cloud's data analysis tools to uncover new value in sales data?
2. What role does machine learning play in discovering new insights from existing datasets?
3. Describe a real-world scenario where leveraging insights could lead to significant business advantage.
4. How can the discovery of new value in data redefine a company's competitive strategy?
5. What are the fundamental differences between raw data and insights in the context of data analysis?

TOPIC: RELIABILITY AT SCALE SCALE

DESCRIPTION AND IN-DEPTH EXPLANATION:
Reliability at scale refers to the ability of large-scale systems to maintain stability, availability, and performance as they grow. In the realm of Google Cloud, reliability is paramount, particularly for businesses with vast numbers of users, global reach, or critical applications. Google Cloud infrastructure is designed to support reliable operations at immense scale through a combination of robust architecture, redundancy, and global data centers.

Reliability at scale is achieved through practices such as load balancing, auto-scaling, and failover systems that ensure continuity of service despite unexpected spikes in demand or hardware failures. Furthermore, Google's globally consistent infrastructure ensures geographic resilience, enabling data queries or migrations across data centers without downtime. This infrastructure is bolstered by Google Cloud’s networking capabilities, including Virtual Private Cloud (VPC) for secure, scalable, and flexible networking.

RELATED CONCEPTS TO KNOW:
SRE, or Site Reliability Engineering, is a critical related concept that encompasses the application of software engineering principles to operations. It focuses on building scalable and highly reliable systems. SRE practices are employed to automate tasks, manage infrastructure efficiently, and reduce downtime, which is crucial for maintaining reliability at scale. Google Cloud's internal SRE methodologies are leveraged to maintain high uptime and reliability across its suite of services.

REAL-WORLD EXAMPLES:
A streaming service operating on Google Cloud must ensure that users experience uninterrupted service despite significant global demand variations. Through automatic scaling and load balancing provided by Google Cloud, the service can dynamically allocate resources to handle peak loads, ensuring a consistent user experience. Additionally, by deploying containerized microservices using Kubernetes Engine, the service can ensure resilience against potential outages or system failures.

GUIDE QUESTIONS:
1. What are the key practices involved in maintaining reliability at scale in Google Cloud?
2. How does Site Reliability Engineering enhance the efficiency and stability of cloud operations?
3. Describe a situation where a failure in reliability at scale can impact business operations.
4. How does Google Cloud's infrastructure ensure geographic resilience and minimize downtime?
5. What are the benefits of using auto-scaling and load balancing in a cloud-native application?

TOPIC: AUTHENTICATION

DESCRIPTION AND IN-DEPTH EXPLANATION:
Authentication is the process of verifying the identity of a user or system, serving as the first line of defense in securing a cloud environment. In Google Cloud, authentication involves multiple mechanisms to ascertain that the entities accessing resources are who they claim to be. Security frameworks and protocols such as OAuth 2.0, OpenID Connect, and multi-factor authentication (MFA) are integral to safeguarding data and services against unauthorized access.

Google Identity provides comprehensive identity and access management capabilities, allowing businesses to implement effective authentication processes across their applications. By integrating these authentication protocols, organizations can ensure secure and streamlined user experiences while complying with various regulatory requirements.

RELATED CONCEPTS TO KNOW:
Authorization is closely related to authentication and refers to determining what an authenticated user is permitted to do. While authentication verifies who the user is, authorization determines access levels and permissions within the system. Google Cloud utilizes Identity and Access Management (IAM) to control permissions effectively. Beyond authentication and authorization, auditing is crucial as it involves tracking and recording user activities to detect anomalies and meet compliance needs.

REAL-WORLD EXAMPLES:
A financial services company implementing Google Cloud can use authentication services to verify user identities before allowing access to sensitive customer data. By utilizing multi-factor authentication, the risk of unauthorized access is significantly reduced. Similarly, an enterprise utilizing Google Workspace can employ OAuth 2.0 to allow users securely access third-party applications without exposing their credentials.

GUIDE QUESTIONS:
1. How do authentication and authorization differ in the context of cloud security?
2. Why is multi-factor authentication critical in securing cloud applications?
3. Discuss the role of Google Identity in facilitating secure authentication processes.
4. How can effective authentication protocols prevent data breaches in a cloud environment?
5. Explain how auditing complements authentication and authorization in a comprehensive security strategy.

TOPIC: ML PROBLEM TYPES

DESCRIPTION AND IN-DEPTH EXPLANATION:
"ML problem types" categorizes the different challenges or tasks that machine learning models can address. In the Google Cloud ecosystem, machine learning (ML) is a vital technological pillar that enables businesses to automate processes, predict outcomes, and improve decision-making. ML problem types include classification, regression, clustering, and reinforcement learning.

Each problem type addresses specific business needs. For instance, classification involves predicting the category a data point falls into, regression predicts continuous values, clustering groups similar data points, and reinforcement learning focuses on training models through trial and error. Understanding these problem types is essential for businesses to correctly frame their AI projects and optimize results using Google Cloud's AI services.

RELATED CONCEPTS TO KNOW:
AI Fundamentals are foundational concepts that underpin machine learning and artificial intelligence systems. Such fundamentals include understanding algorithms, data preprocessing, model training, and evaluation. Google Cloud provides resources and platforms like AI Platform and TensorFlow to build, train, and deploy ML models efficiently. Delving into AI fundamentals enhances one’s ability to structure AI strategies effectively and leverage ML problem types to solve complex business challenges.

REAL-WORLD EXAMPLES:
An e-commerce company may utilize classification for sentiment analysis to categorize customer reviews as positive, neutral, or negative, enabling better customer relationship management. Similarly, a financial institution predicting stock prices may rely on regression to forecast future values based on past trends. A logistics company optimizing delivery routes might employ clustering to group deliveries by geographical proximity, improving efficiency.

GUIDE QUESTIONS:
1. How do different machine learning problem types address varied business challenges?
2. What are the steps involved in framing a business problem into an ML problem on Google Cloud?
3. Discuss the significance of understanding AI fundamentals in leveraging ML solutions effectively.
4. Why is it important to choose the correct ML problem type when designing an AI solution?
5. How can businesses evaluate the effectiveness of their ML models in solving specific problem types?

=======================================================

Mid-Scores

In [ ]:
import pandas as pd

# File paths
STUDENT_ANSWERS_CSV_PATH = "/content/drive/MyDrive/Colab Notebooks/mid_score_test.csv"
CDL_TOPIC_DATASET_PATH = "/content/drive/MyDrive/Colab Notebooks/cdl-TOPIC_DATASET.xlsx"
QUIZ_ANSWER_KEY_PATH = "/content/drive/MyDrive/Colab Notebooks/quiz_answer_key.csv"

# Column name config
COL_QUESTION_ID = 'question_id'
COL_STUDENT_ANSWER = 'answer'
COL_CORRECT_ANSWER = 'correct_answer_label'

def generate_personalized_study_guide(csv_path, curriculum_path, answer_key_path):
    print(f"Loading student answers from: {csv_path}")
    print(f"Loading answer key from: {answer_key_path}")
    print(f"Loading curriculum dataset from: {curriculum_path}")

    # Load datasets
    try:
        student_answers = pd.read_csv(csv_path)
        answer_key = pd.read_csv(answer_key_path)
        cdl_curriculum = pd.read_excel(curriculum_path)
    except FileNotFoundError as e:
        return f"File not found error: {e}\nPlease check the paths and try again."

    # Check student answers against the answer key
    if COL_QUESTION_ID not in student_answers.columns or COL_QUESTION_ID not in answer_key.columns:
        return f"Error: Both CSVs must contain a '{COL_QUESTION_ID}' column to match them up."

    merged = pd.merge(student_answers, answer_key, on=COL_QUESTION_ID, how='left')

    if COL_STUDENT_ANSWER not in merged.columns or COL_CORRECT_ANSWER not in merged.columns:
        return f"Error: Check column names. Could not find '{COL_STUDENT_ANSWER}' or '{COL_CORRECT_ANSWER}' after merging."

    # Create a boolean correctness column by comparing strings (ignoring case and whitespace)
    merged['is_correct'] = (
        merged[COL_STUDENT_ANSWER].astype(str).str.strip().str.lower() ==
        merged[COL_CORRECT_ANSWER].astype(str).str.strip().str.lower()
    ).astype(int)

    # Filter questions for the study guide
    incorrect_answers = merged[merged['is_correct'] == 0]
    perfect_score = False

    if incorrect_answers.empty:
        print("Perfect score detected! Generating a comprehensive review guide based on all answered questions...")
        target_questions = merged
        perfect_score = True
    else:
        print(f"Found {len(incorrect_answers)} incorrect answers. Gathering context from Hybrid RAG...")
        target_questions = incorrect_answers

    # Gather context using our Hybrid RAG for the targeted topics/questions
    rag_context = ""
    for index, row in target_questions.iterrows():
        # Use the question ID or topic to search our RAG
        search_query = str(row.get('topic', f"Question ID {row.get(COL_QUESTION_ID)} concept"))

        # Fetch top 3 most relevant context blocks to expand the scope
        rag_results = hybrid_search(search_query, top_k=3)

        # Append the retrieved content (including Related Topics) to our context
        for _, q_row in rag_results.iterrows():
            rag_context += f"Topic: {q_row.get('Topic', 'Unknown')}\n"
            rag_context += f"Definition: {q_row.get('Definition', '')}\n"
            # Include related topics from the dataset so the LLM can expand the study guide
            rag_context += f"Related Topics to Mention: {q_row.get('Related Topics', 'None')}\n\n"

    # Inject context into LLM (OpenAI GPT API)
    print("Generating study guide via OpenAI API...")

    if perfect_score:
        prompt_intro = "A student has just taken a practice exam and got a perfect score! Provide an extremely comprehensive, advanced reviewer to reinforce and deepen their knowledge on these topics."
    else:
        prompt_intro = "A student has just taken a practice exam and got several topics wrong. Provide a personalized, extensively detailed reviewer to help them deeply understand their mistakes and master the material."

    prompt = f"""
    You are an expert Google Cloud Digital Leader tutor.
    {prompt_intro}

    CRITICAL INSTRUCTIONS:
    1. CLEAN PLAIN TEXT ONLY: DO NOT use any Markdown formatting. NO asterisks (*), NO hashtags (#), NO underscores (_), and NO bold/italic formatting. Use ALL CAPS for headers, simple numbers (1., 2.), and clean line breaks to structure your output.
    2. BE HIGHLY DESCRIPTIVE & CONTEXTUAL: Provide a massive, extensive, and comprehensive reviewer. Do not give brief summaries. Tie everything back to Google Cloud principles, business values, and real-world environments.
    3. MENTION RELATED TOPICS: In the context below, there are "Related Topics" listed for the main concepts. You MUST weave these related topics into your explanations to expand the length and depth of the study guide. Show how they connect!
    4. NO CRITIQUE: DO NOT critique the quiz itself or mention test format. Focus purely on teaching.

    For every topic the student needs to review, you MUST format the output strictly as follows:

    TOPIC: [TOPIC NAME IN ALL CAPS]

    DESCRIPTION AND IN-DEPTH EXPLANATION:
    (A comprehensive and highly detailed explanation of the concept and its contextual importance in Google Cloud.)

    RELATED CONCEPTS TO KNOW:
    (Explain the related topics provided in the context. Show how they interconnect with the main topic to build a broader understanding.)

    REAL-WORLD EXAMPLES:
    (Detailed, practical examples illustrating exactly how this concept is applied in a business or cloud environment.)

    GUIDE QUESTIONS:
    (3 to 5 thought-provoking questions to thoroughly test their understanding.)

    Context from Curriculum (Including Related Topics):
    {rag_context}

    Please provide the structured, extensive, plain-text reviewer now.
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are a highly professional, exhaustive, and helpful cloud tutor."},
                {"role": "user", "content": prompt}
            ],
            max_completion_tokens=4000
        )
        llm_response_content = response.choices[0].message.content
        print(f"LLM Response Content Length: {len(llm_response_content)}")
        print(f"LLM Response Content (first 500 chars):\n{llm_response_content[:500]}")
        return llm_response_content
    except Exception as e:
        return f"Error calling OpenAI API: {e}"

# EXECUTE THE PIPELINE

final_study_guide = generate_personalized_study_guide(STUDENT_ANSWERS_CSV_PATH, CDL_TOPIC_DATASET_PATH, QUIZ_ANSWER_KEY_PATH)
print("\n================ GENERATED STUDY GUIDE ================\n")
print(final_study_guide)
print("\n=======================================================\n")

Loading student answers from: /content/drive/MyDrive/Colab Notebooks/mid_score_test.csv
Loading answer key from: /content/drive/MyDrive/Colab Notebooks/quiz_answer_key.csv
Loading curriculum dataset from: /content/drive/MyDrive/Colab Notebooks/cdl-TOPIC_DATASET.xlsx
Found 15 incorrect answers. Gathering context from Hybrid RAG...
Generating study guide via OpenAI API...
LLM Response Content Length: 10684
LLM Response Content (first 500 chars):
TOPIC: NEW VALUE VALUE

DESCRIPTION AND IN-DEPTH EXPLANATION:
The concept of "New Value Value" in Google Cloud refers to the process of uncovering previously hidden benefits within data. Companies hold vast amounts of data, yet many fail to leverage it effectively to garner deeper insights that drive business growth and innovation. Google Cloud offers robust analytics and machine learning tools that enable organizations to sift through data silos, extract valuable insights, and translate them in

================ GENERATED STUDY GUIDE ================

TOPIC: NEW VALUE VALUE

DESCRIPTION AND IN-DEPTH EXPLANATION:
The concept of "New Value Value" in Google Cloud refers to the process of uncovering previously hidden benefits within data. Companies hold vast amounts of data, yet many fail to leverage it effectively to garner deeper insights that drive business growth and innovation. Google Cloud offers robust analytics and machine learning tools that enable organizations to sift through data silos, extract valuable insights, and translate them into actionable business strategies. The significance of "New Value Value" lies in its ability to transform raw data into a strategic asset. By doing so, organizations can identify new revenue streams, enhance customer experiences, optimize operations, and maintain a competitive edge in the market.

RELATED CONCEPTS TO KNOW:
Insights: Insights are the actionable results derived from data analysis. They form the backbone of making informed business decisions. With Google Cloud's powerful analytics tools such as BigQuery, businesses can perform fast SQL queries and gain insights from massive datasets in real-time. Machine learning services like AutoML further enable the synthesis of high-level insights by allowing users to build custom models that reveal patterns and trends not immediately apparent to the human eye. Understanding insights and how to derive them from raw data is crucial for fully realizing the potential of the data held by an organization.

REAL-WORLD EXAMPLES:
Consider an e-commerce company utilizing Google Cloud's BigQuery to analyze customer purchase behavior across different platforms. By finding correlations between buying trends and seasonal promotions, the company can create targeted marketing strategies that boost sales during specific times of the year. Similarly, a logistics firm might employ predictive analytics to foresee supply chain disruptions, thus improving operational timelines and cost efficiency.

GUIDE QUESTIONS:
1. How can utilizing data analytics in Google Cloud help a business discover new value in its operations?
2. What role do insights play in transforming raw data into strategic business decisions?
3. Can you think of a way a company might use Google Cloud's machine learning tools to uncover hidden value in customer data?
4. Discuss how the process of deriving insights is critical in creating new business opportunities.
5. How does Google Cloud help businesses maintain a competitive edge through data analytics?

TOPIC: RELIABILITY AT SCALE

DESCRIPTION AND IN-DEPTH EXPLANATION:
Reliability at scale refers to the capacity of large systems to maintain stability, function seamlessly, and deliver consistent performance even as the scale of operations or the number of users increase. Within Google Cloud, this is a fundamental principle, ensuring that services remain available and performant under varying loads and potential failures. This reliability is achieved through infrastructure that incorporates redundancy, automated failovers, and globally distributed networks. Embracing a microservices architecture, utilizing Kubernetes for container orchestration, and leveraging managed services like Cloud Spanner and Cloud Pub/Sub, Google Cloud aids businesses in achieving reliability at unprecedented scales. This, in turn, is vital for maintaining user trust and ensuring critical services remain operational across diverse and distributed environments.

RELATED CONCEPTS TO KNOW:
SRE (Site Reliability Engineering): SRE is a discipline that incorporates aspects of software engineering and applies them to infrastructure and operations problems. Google Cloud's approach to SRE involves addressing reliability concerns through automation, measuring performance metrics, and implementing error budgets. Understanding SRE is essential for sustaining service reliability at scale, ensuring services meet performance and reliability goals through proactive planning and robust engineering practices.

REAL-WORLD EXAMPLES:
Consider a global online streaming service that relies on Google Cloud's distributed storage and content delivery networks to deliver seamless, uninterrupted content to millions of users. The company employs SRE principles to manage and automate load balancing during peak usage times, ensuring viewers consistently receive high-quality streams without interruptions.

GUIDE QUESTIONS:
1. What are the key strategies Google Cloud uses to ensure reliability at scale?
2. How does Site Reliability Engineering (SRE) contribute to the stability of large systems?
3. Describe a scenario where reliability at scale is crucial for business operations.
4. Discuss the importance of automation and observability in maintaining reliable cloud services.
5. How do Google Cloud’s managed services facilitate reliability and scalability for enterprises?

TOPIC: AUTHORIZATION

DESCRIPTION AND IN-DEPTH EXPLANATION:
Authorization in the context of Google Cloud refers to determining what a user is permitted to do within a system. Once a user’s identity is authenticated, authorization establishes their access rights and permissions. On Google Cloud, Identity and Access Management (IAM) provides this capability by allowing granular control over cloud resources. Administrators can assign roles and permissions at the project, folder, or resource level, ensuring the principle of least privilege is upheld. Authorization is critical for security and compliance, ensuring that sensitive information and system functionalities are accessible only to users with explicit permission.

RELATED CONCEPTS TO KNOW:
Auditing: In conjunction with authorization, auditing is a critical function that logs and reviews system activity to ensure compliance and security. Google Cloud Audit Logs provide detailed insights into the actions performed by users, helping organizations detect unauthorized activities and investigate security breaches. Auditing complements authorization by offering a retrospective view of access and actions within cloud environments.

REAL-WORLD EXAMPLES:
A financial institution using Google Cloud IAM to control access to sensitive customer data can ensure that only authorized personnel can view or modify account information. Through regular audit logs, they can monitor access patterns and detect any attempts to compromise customer data privacy.

GUIDE QUESTIONS:
1. Explain the difference between authentication and authorization in cloud security.
2. How does IAM facilitate secure and efficient access management in Google Cloud?
3. Why is auditing an essential aspect of robust authorization practices?
4. Discuss how maintaining the principle of least privilege enhances security within a cloud environment.
5. How can companies ensure effective monitoring and auditing of access to their cloud resources?

TOPIC: AUTHENTICATION

DESCRIPTION AND IN-DEPTH EXPLANATION:
Authentication in Google Cloud involves verifying a user's identity before granting access to resources and services. It is the first line of defense against unauthorized access, ensuring that only valid entities can interact with cloud systems. Google Cloud supports various authentication methods, including OAuth 2.0 for secure API access, OpenID Connect for user authentication, and Cloud Identity, which allows centralized identity management. Through effective authentication mechanisms, organizations can uphold security and maintain user trust by ensuring proper user verification and access control.

RELATED CONCEPTS TO KNOW:
Authorization: Once a user is authenticated, authorization determines what resources and actions the user can access within the system. Strong authentication protocols provide the foundation upon which reliable authorization systems are built, together ensuring comprehensive cloud security.

REAL-WORLD EXAMPLES:
An enterprise deploying an internal application on Google Cloud might integrate with Cloud Identity to authenticate its employees. By doing so, they ensure that access to the application is restricted to legitimate users, improving both security and access compliance across departments.

GUIDE QUESTIONS:
1. What are the primary methods of authentication supported by Google Cloud, and how do they secure user identity?
2. How does the relationship between authentication and authorization enhance cloud security?
3. In what way does Cloud Identity streamline the user authentication process for enterprises?
4. Describe the role of OAuth 2.0 in securing API interactions in Google Cloud.
5. Why is strong authentication a crucial aspect of maintaining data integrity and security?

TOPIC: ML PROBLEM TYPES

DESCRIPTION AND IN-DEPTH EXPLANATION:
Machine Learning (ML) problem types refer to the different categories of problems that artificial intelligence (AI) solutions are built to solve. In Google Cloud, identifying the right problem type is crucial for successful ML deployment. Common ML problem types include classification, regression, clustering, and time series prediction. Classification involves categorizing data into predefined labels, while regression predicts continuous values. Clustering groups similar items together without predefined categories, and time series prediction anticipates future values based on historical data. The correct identification of a problem type guides data scientists in selecting suitable algorithms and models, resulting in high-performance ML solutions.

RELATED CONCEPTS TO KNOW:
AI Fundamentals: AI fundamentals underpin the development of intelligent systems capable of mimicking human tasks. Comprehending AI fundamentals, such as understanding the capabilities and limitations of ML models, is vital for selecting the right problem types and designing effective solutions. Google Cloud facilitates this through tools like TensorFlow and AI Platform, empowering developers to harness AI's full potential.

REAL-WORLD EXAMPLES:
A healthcare provider might use classification algorithms to identify patients at high risk of specific diseases based on historical health data, enabling early intervention and preventive care. Conversely, an e-commerce site might employ regression to forecast sales and optimize inventory levels.

GUIDE QUESTIONS:
1. How do different ML problem types determine the approach to developing an AI solution?
2. Why is understanding AI fundamentals important when dealing with ML problem types?
3. Describe a scenario where classification would be the appropriate ML problem type.
4. How does Google Cloud support diverse ML problem types through its suite of AI tools?
5. Explain the impact of selecting an incorrect ML problem type on the performance of an AI solution.

=======================================================

In [ ]:
import openai
from google.colab import userdata

OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')
client = openai.OpenAI(api_key=OPENAI_API_KEY)

def ask_cdl_bot():
    print("Hello! I am your Google Cloud Digital Leader assistant. Ask me anything about the CDL curriculum.")
    print("Type 'exit' or 'quit' to end the conversation.")

    while True:
        user_query = input("\nAsk a question about the Google Cloud Digital Leader topics: ")

        if user_query.lower() in ['exit', 'quit']:
            print("Thank you for chatting! Goodbye.")
            break

        print("\nSearching for relevant context...")

        try:
            rag_results = hybrid_search(user_query, top_k=3)
        except Exception as e:
            print(f"Error during search: {e}")
            continue

        if rag_results.empty:
            print("No relevant context found in the CDL curriculum.")
            continue

        context_str = ""
        for index, row in rag_results.iterrows():
            context_str += f"Topic: {row.get('Topic', 'Unknown')}\n"
            context_str += f"Definition: {row.get('Definition', '')}\n"
            context_str += f"Related Topics: {row.get('Related Topics', 'None')}\n\n"

        prompt = f"""
        You are an expert Google Cloud Digital Leader tutor.
        Your task is to answer the user's question using the provided context as your factual foundation.
        However, DO NOT just repeat the context. You must generate a highly detailed, conversational, and comprehensive explanation of the concept using your advanced LLM capabilities.
        Provide real-world examples, elaborate on why the concept matters in cloud computing, and ensure your answer is rich and engaging (at least 2-3 paragraphs).

        CRITICAL INSTRUCTION: You must ONLY answer questions related to Google Cloud, cloud computing, and topics found in the provided CDL dataset context. If the user asks a question outside of these topics (e.g., general programming, math, history), politely refuse to answer and remind them that you are a Google Cloud Digital Leader tutor.

        Context from curriculum:
        {context_str}

        User Question: {user_query}
        """

        print("Generating explanation...")

        try:
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": "You are a highly capable and conversational cloud tutor. You provide detailed explanations that go beyond just quoting facts. You ONLY answer questions related to Google Cloud and cloud computing."},
                    {"role": "user", "content": prompt}
                ],
                max_completion_tokens=800,
                temperature=0.7
            )
            answer = response.choices[0].message.content
            print("\n================ EXPLANATION ================\n")
            print(answer)
            print("\n=============================================\n")
        except Exception as e:
            print(f"Error calling OpenAI API: {e}")


ask_cdl_bot()

Hello! I am your Google Cloud Digital Leader assistant. Ask me anything about the CDL curriculum.
Type 'exit' or 'quit' to end the conversation.

Searching for relevant context...
Generating explanation...

================ EXPLANATION ================

Cloud service models are fundamental to understanding how cloud computing operates and are typically categorized into three primary types: Infrastructure as a Service (IaaS), Platform as a Service (PaaS), and Software as a Service (SaaS). Each model offers varying levels of control, flexibility, and management, catering to different business needs and technical requirements.

**Infrastructure as a Service (IaaS)** is the most flexible cloud model, providing virtualized computing resources over the internet. With IaaS, organizations can rent IT infrastructure—servers, storage, and networking—on a pay-as-you-go basis. This model is akin to managing your own data center but without the overhead of physical maintenance. IaaS is ideal for businesses that require highly customizable and scalable computing environments. For example, a company looking to test and develop software applications without investing in physical hardware might choose Google Cloud's Compute Engine, which offers scalable virtual machines.

**Platform as a Service (PaaS)** offers a cloud-based platform with tools to develop, test, and deploy applications quickly and efficiently. It's designed to simplify the process of application development by providing a runtime environment and development tools without the complexity of managing the underlying infrastructure. This model is perfect for developers who want to focus on writing code and building functionality rather than managing software updates and hardware. Google App Engine is a prime example, allowing developers to build applications in various languages and scale them automatically as demand grows.

**Software as a Service (SaaS)** delivers software applications over the internet on a subscription basis. This model removes the need for users to install, maintain, and manage software, as everything is handled through a web browser. It's particularly beneficial for businesses aiming to minimize IT overhead and provide employees with easy access to software tools. Applications like Google Workspace exemplify SaaS, offering a suite of productivity tools like Gmail, Docs, and Drive that enhance collaboration without needing local installations.

These models collectively enable businesses to leverage cloud computing's scalability, cost efficiency, and flexibility, allowing them to focus more on their core operations and less on IT management.

=============================================


Searching for relevant context...
Generating explanation...

================ EXPLANATION ================

I'm here to assist with questions related to Google Cloud and cloud computing. If you have questions about how IoT (Internet of Things) integrates with Google Cloud or its applications in cloud computing, I'd be delighted to help. For example, Google Cloud offers IoT solutions like Cloud IoT Core, which helps you connect, manage, and ingest data from globally dispersed devices, leveraging the power of Google's infrastructure for data processing and analysis. If you have any questions in that direction, feel free to ask!

=============================================


Searching for relevant context...
Generating explanation...

================ EXPLANATION ================

I'm here to assist with questions related to Google Cloud and cloud computing topics. If you have any questions about these areas, such as how Google Cloud's Vision API works or what Service Level Indicators are, feel free to ask!

=============================================


Searching for relevant context...
Generating explanation...

================ EXPLANATION ================

Google Cloud offers a variety of services that are particularly well-suited for Internet of Things (IoT) applications, providing robust solutions for data ingestion, processing, and analytics. Here are some key Google Cloud services that are ideal for IoT:

1. **Cloud IoT Core**: This is a fully managed service that allows you to easily and securely connect, manage, and ingest data from millions of globally dispersed devices. Cloud IoT Core is designed to integrate seamlessly with other Google Cloud services, providing a complete IoT solution. It supports device connections through MQTT and HTTP protocols, which are standard in the IoT industry.

2. **BigQuery**: Known for its powerful data warehousing and analytics capabilities, BigQuery enables organizations to analyze massive datasets with ease and speed. For IoT applications, BigQuery is invaluable for real-time data analysis, allowing businesses to derive insights from the vast amounts of data generated by connected devices.

3. **Pub/Sub**: Cloud Pub/Sub is a messaging service that facilitates real-time messaging between applications. It is highly scalable and can handle large volumes of messages, making it ideal for IoT scenarios where devices need to communicate and transmit data to the cloud for processing and analysis.

4. **Dataflow**: This service is used for stream and batch data processing. In the context of IoT, Dataflow can process the continuous stream of data from devices, perform transformations, and push the processed data to storage or for further analysis.

5. **Bigtable**: Google Cloud Bigtable is a fully managed, scalable NoSQL database suitable for large analytical and operational workloads. It is perfect for IoT use cases that require low-latency access to large datasets, such as time-series data from sensors.

6. **Firebase**: While primarily known for mobile and web app development, Firebase also provides robust real-time data synchronization capabilities that can be applied to IoT, particularly for applications that require seamless data updates across devices.

These services collectively provide the infrastructure and tools needed to build comprehensive IoT solutions. They help organizations not only manage and analyze data from connected devices but also ensure the scalability, reliability, and security of their IoT deployments. By leveraging these Google Cloud services, businesses can focus on innovation and building value-added features for their IoT applications.

=============================================